default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: pay_day_server_development
test:
  <<: *default
  database: pay_day_server_test
production:
  <<: *default
  database: pay_day_server_production
  username: pay_day_server
  password: <%= ENV['PAY_DAY_SERVER_DATABASE_PASSWORD'] %>
